version: "3.9"

services:
  monorepo:
    build: .
    init: true
    volumes:
      - ..:/workspace
      - node_modules:/workspace/node_modules
      - pnpm-store:/pnpm-store
    command: sleep infinity
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Configure pnpm to install its global/dlx binaries into /pnpm-store
      # instead of the default ~/.local/share/pnpm. We mount /pnpm-store
      # as a named volume (see below) so that:
      #   1. Installed pnpm tools (e.g. via "pnpm dlx" or "pnpm add -g")
      #      are persisted across container rebuilds.
      #   2. The host system (WSL) stays clean, since no files are written
      #      to your home directory.
      # Adding /pnpm-store to PATH makes those binaries directly runnable
      # without needing the full path.
      PNPM_HOME: /pnpm-store
      PATH: /pnpm-store:$PATH
      # Tell starship where to find its config file
      STARSHIP_CONFIG: /workspace/.devcontainer/starship.toml
      # Make CLI tools like psql easier
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
      PGPORT: 5432

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  node_modules:
  pnpm-store:
  postgres_data:
